title: Bhargav Madishetti
logo: /assests/img/headshot_circle.png
description: Data Analyst | S&P Global | Media and Communication Industry Content | Data Operations & Management
show_downloads: true
theme: jekyll-theme-minimal
