title: Bhargav Madishetti
logo: C:\My_Files\RRB
description: Data Analyst|S&P Global|Media and Communication Industry Content|Data Operations & Management
show_downloads: true
theme: jekyll-theme-minimal
